version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.16
  build:
    commands:
      - cd website-watcher-app
      - go build -o website-watcher-app main.go
      - cd ..
      - sam package --template-file template.yaml --s3-bucket codepipeline-applications --output-template-file packaged-template.yml
  post_build:
    commands:
      - sam deploy --template-file packaged-template.yml --stack-name website-watcher-stack --capabilities CAPABILITY_IAM
artifacts:
  files:
    - packaged-template.yml
