version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket codepipeline-applications --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
