AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  website-watcher
  
  Sample SAM Template for website-watcher

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  WebsiteWatcherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: website-watcher-app/
      Handler: website-watcher-app
      Runtime: go1.x
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(1 day)'
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          BUCKET: !Ref WebsiteWatchBucket
  WebsiteWatchBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: website-watcher-bucket

Outputs:
  WebsiteWatcherFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt WebsiteWatcherFunction.Arn
